language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: "kmindi-github" # the key of the org you chose at step #3
before_install:
  - chmod +x gradlew
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner
